import { Product } from '@/types/product';

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Baskets Vintage Pro',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    description: 'Chaussures vintage classiques avec technologie confortable',
    category: 'shoes',
    rating: 4.8,
    reviewCount: 243,
    stock: 15,
    discount: 10,
    isNew: false,
    tags: ['classic', 'vintage', 'comfortable'],
  },
  {
    id: '2',
    title: 'Chaussures Sport Elite',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1525966222134-fceb466e6e85?w=400',
    description: 'Chaussures de sport haute performance pour tous les athlètes',
    category: 'shoes',
    rating: 4.9,
    reviewCount: 512,
    stock: 28,
    isNew: true,
    tags: ['sport', 'performance', 'breathable'],
  },
  {
    id: '3',
    title: 'Sneakers Moderne Urbain',
    price: 99.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    description: 'Design contemporain parfait pour la ville et le casual',
    category: 'shoes',
    rating: 4.6,
    reviewCount: 189,
    stock: 32,
    discount: 15,
    tags: ['urban', 'modern', 'casual'],
  },
  {
    id: '4',
    title: 'Sac à Dos Ergonomique',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    description: 'Sac à dos confortable avec compartiments organisés',
    category: 'accessories',
    rating: 4.7,
    reviewCount: 156,
    stock: 45,
    isNew: true,
    tags: ['backpack', 'ergonomic', 'organized'],
  },
  {
    id: '5',
    title: 'Casquette Lifestyle',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    description: 'Casquette tendance pour tous les styles',
    category: 'accessories',
    rating: 4.4,
    reviewCount: 87,
    stock: 60,
    discount: 20,
    tags: ['cap', 'lifestyle', 'trendy'],
  },
  {
    id: '6',
    title: 'T-Shirt Coton Premium',
    price: 44.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    description: 'T-shirt en coton biologique confortable et durable',
    category: 'apparel',
    rating: 4.5,
    reviewCount: 234,
    stock: 89,
    tags: ['tshirt', 'cotton', 'sustainable'],
  },
  {
    id: '7',
    title: 'Veste Outdoor Adventure',
    price: 189.99,
    image: 'https://images.unsplash.com/photo-1539533057440-7d8f44242c88?w=400',
    description: 'Veste imperméable et respirante pour toutes les aventures',
    category: 'apparel',
    rating: 4.9,
    reviewCount: 421,
    stock: 22,
    isNew: true,
    tags: ['jacket', 'waterproof', 'adventure'],
  },
  {
    id: '8',
    title: 'Ballon Football Pro',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400',
    description: 'Ballon de football professionnel avec technologie anti-dépliage',
    category: 'sports',
    rating: 4.7,
    reviewCount: 312,
    stock: 35,
    discount: 5,
    tags: ['football', 'professional', 'sports'],
  },
  {
    id: '9',
    title: 'Raquette Badminton Carbone',
    price: 74.99,
    image: 'https://images.unsplash.com/photo-1624526267942-ab67cb75ffa1?w=400',
    description: 'Raquette légère en fibre de carbone pour meilleure performance',
    category: 'sports',
    rating: 4.6,
    reviewCount: 143,
    stock: 18,
    tags: ['badminton', 'carbon', 'lightweight'],
  },
  {
    id: '10',
    title: 'Tapis Yoga Premium',
    price: 54.99,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    description: 'Tapis de yoga écologique avec excellente adhérence',
    category: 'sports',
    rating: 4.8,
    reviewCount: 267,
    stock: 51,
    isNew: true,
    tags: ['yoga', 'eco-friendly', 'grip'],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'Tous', icon: '🏠' },
  { id: 'shoes', label: 'Chaussures', icon: '👟' },
  { id: 'accessories', label: 'Accessoires', icon: '👜' },
  { id: 'apparel', label: 'Vêtements', icon: '👕' },
  { id: 'sports', label: 'Sports', icon: '⚽' },
];
